### ISSUE TITLE
Support in mysdebug node to decode "send:" and "read:" debug messages

### ISSUE THREAD

**Issue by fallberg** [tbowmo/node-red-contrib-mysensors#1]
It would be great if data passed through mysdebug that matches a "read:" or "write" debug print was decorated as well.
That is, this:
```
send: 0-0-4-4 s=144,c=1,t=36,pt=0,l=1,sg=1,st=ok:0
```
would become this (or something similar):
```
send: sender:0-last:0-to:4-dest:4 childId=144,command=SET,SubType=V_LOCK_STATUS,PayloadType=P_STRING,length=1,SIGNED,st=ok:0
```

**Comment by tbowmo** [comment]
It should be implemented now in 0.7.5
