### ISSUE TITLE
Add second output to controller

### ISSUE THREAD

**Issue by Mirodin** [tbowmo/node-red-contrib-mysensors#16]
Thanks for fixing #15 now everything works as expected.

However if you are open to suggestions it would be nice if the controller could act as a message filter by itself having two outputs.

1. The first one returns requests which are processed by the controller itself and should go right back to MQTT.
2. A second output would forward all messages the controller can not handle (like all other messages).

This way the controller decides on what request to act and which requests to send down the flow so one does not need to use a switch statement in front of the controller to decide what to do. In case of future updates internal messages would not end up in other flows if the controller could handle them already.

**Comment by tbowmo** [comment]
I don't see a real usecase for this. You can always filter messages when listening for them in your flow.

F.ex. listening for all mysensor  set commands on MQTT:
`mys-in/+/+/1/#
`
Putting above into a MQTT input node, will only give you sensor values from all your nodes.
If using a serial gateway is of course a bit different, but also doable with a function node or the like.

As an example, see the flow snippet below, where I listen multiple times for mys-in.. topics, each getting the data in..

![image](https://user-images.githubusercontent.com/5305197/41739314-fe169a84-7594-11e8-90a0-b41300a2fc04.png)

**Comment by Mirodin** [comment]
The MQTT gateway is still somewhat new for me, I did not know that I get those informations from the topics. If it is that easy you are right, there is no point in adding another filter inside controller node.

**Comment by tbowmo** [comment]
That is why I recommend mqtt, if you want to use nodered. I still use my serial gateway, but I convert it to mqtt with nodered, following mysensors topic format. It made my life so much easier, than when I was using serial only in nodered.
