### ISSUE TITLE
How to send a float value to a sensor?

### ISSUE THREAD

**Issue by willemx** [tbowmo/node-red-contrib-mysensors#18]
Could you please explain or  provide an example on how to use the encapsulate node to send a float value to a sensor?

**Comment by willemx** [comment]
Never mind, I did some digging in the MySensors code and stumbled upon the function `protocolMyMessage2MQTT` where (I think) the output from the encapsulated MQTT message is translated into an MySensors network message. It seems that every MQTT payload is translated by the gateway into a message with a 'string' payload type.

**Comment by tbowmo** [comment]
All values are sent in plain text at the mysensors protocol level, and then converted to float etc. on each node (Not that efficient, but that's how it's done right now).
