### ISSUE TITLE
Wrong type values

### ISSUE THREAD

**Issue by 6wheels** [tbowmo/node-red-contrib-mysensors#24]
Hi,
I recently tried to use V_PERCENTAGE type, and I noticed that it is set to a value of 4 instead of 3.
I also found that V_LIGHT does not exist (anymore?).
I didn't check the other values.

![image](https://user-images.githubusercontent.com/36991993/67710243-e0607b80-f9bf-11e9-8bf5-817df43ea5ea.png)

**Comment by huexpub** [comment]
yes, with set Child type , type var is 24 ,choose var1  msg return  27,  so it use choose num's id  not type's id ?

**Comment by tbowmo** [comment]
Sorry, missed the first bug report in the mail stream. Indeed it seems that it makes an offset for the values that is transmitted.

I'll see if I can get a fix made later today

**Comment by tbowmo** [comment]
@huexpub, @6wheels  I have released version 3.2.2 to npmjs, which should fix this issue

**Comment by tbowmo** [comment]
Make that 3.3.1 that is released, somehow I had screwed up my version numbering. Should be fixed now.
