### ISSUE TITLE
Payload should be set as float instead of string for most message types

### ISSUE THREAD

**Issue by 6wheels** [tbowmo/node-red-contrib-mysensors#27]
Hi,

I noticed that payload values are set as string. I think this should be set to number (float, integer, etc.) for most of the message types.
For example, a temperature or humidity value will always be a float.

This avoids doing a conversion in our flows.

What do you think?
Cheers

**Comment by magtimmermans** [comment]
+1

**Comment by tbowmo** [comment]
I'll see if I can get around to it the coming week.

**Comment by 6wheels** [comment]
No answer, no support, not using anymore, closing...
