### ISSUE TITLE
decode-encode.js with a problem....

### ISSUE THREAD

**Issue by ghost** [tbowmo/node-red-contrib-mysensors#3]
These line:
pl = msg.nodeId + ";" + msg.childSensorId + ";" + msg.messageType + ";" + msg.ack + ";" + msg.subType + ";" + msg.payload;
Should be:
  pl = msg.nodeId + ";" + msg.childSensorId + ";" + msg.messageType + ";" + msg.ack + ";" + msg.subType + ";" + msg.payload + "\n";

This way the message gets to the node, the first one doesn't get there.

Thanks,
Rui.

**Comment by tbowmo** [comment]
I would like to keep this clean of any line formatting, as I use it for numerous other things. 

this can also be achieved in the serial port configuration. As it can be configured to add \n to all packaged sent through it.
