### ISSUE TITLE
Conflict with node-red-node-sqlite

### ISSUE THREAD

**Issue by rikki78** [tbowmo/node-red-contrib-mysensors#31]
Hi,
I recently have a conflict with node-red-node-sqlite in my node red installation.
It seems it can't be installed together with node-red-contrib-sqlitedb. Is it possible to modify the mysensors node so it works with node-red-node-sqlite?

**Comment by tbowmo** [comment]
Sorry, had almost forgotten about this project. But have come back to give it an overhaul.

I'm going to remove sqlite altogether, and use node reds context instead.

#44

**Comment by tbowmo** [comment]
sqlite is no longer a part of this node
